### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by Blaubeermuffin** [ayesc9000/SteamIconFixer#1]
When running the exe, it runs into an error when trying to download the icons:

```bash
Found 9 missing icons.
Do you want to redownload the icons? (y/N): y

Downloading 9 icons...
Traceback (most recent call last):
  File "sif.py", line 169, in <module>
TypeError: can only concatenate str (not "int") to str
[26244] Failed to execute script 'sif' due to unhandled exception!
```

Python 3.12.8 is installed and should be used by default, as seen in the following screenshot as well.

![sif exe error](https://github.com/user-attachments/assets/089e18af-9cc4-4e02-a995-c8a0cb4dee06)

Am I missing something? Does it need to be Python 3.11.x for this script to work? Or is this a proper bug?

**Comment by Blaubeermuffin** [comment]
It seems that casting the variables `streamid` and `response.status_code` into `str()` in lines 169, 178 and 182 fixes the issue mentioned above. 

Now it's just throwing 404 error codes. Seems that steam has moved the resources somewhere else...

**Comment by ayesc9000** [comment]
Hey there, I knew the script would break eventually so I'm currently working on a rewrite that should be far better. I'll try to get something out in the next week.
